/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sponsors: Sponsor;
    staff: Staff;
    gardeners: Gardener;
    areas: Area;
    interventions: Intervention;
    activities: Activity;
    evidenceBundles: EvidenceBundle;
    attestations: Attestation;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    areas: {
      activities: 'activities';
    };
    interventions: {
      activities: 'activities';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sponsors: SponsorsSelect<false> | SponsorsSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    gardeners: GardenersSelect<false> | GardenersSelect<true>;
    areas: AreasSelect<false> | AreasSelect<true>;
    interventions: InterventionsSelect<false> | InterventionsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    evidenceBundles: EvidenceBundlesSelect<false> | EvidenceBundlesSelect<true>;
    attestations: AttestationsSelect<false> | AttestationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    organizationProfile: OrganizationProfile;
    taskCatalog: TaskCatalog;
  };
  globalsSelect: {
    organizationProfile: OrganizationProfileSelect<false> | OrganizationProfileSelect<true>;
    taskCatalog: TaskCatalogSelect<false> | TaskCatalogSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      registerArea: TaskRegisterArea;
      scheduleIntervention: TaskScheduleIntervention;
      commitActivityChain: TaskCommitActivityChain;
      validateIntervention: TaskValidateIntervention;
      publishIntervention: TaskPublishIntervention;
      buildBundle: TaskBuildBundle;
      verifyBundle: TaskVerifyBundle;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  displayName: string;
  roles: ('admin' | 'manager' | 'validator' | 'assessor' | 'authoring' | 'viewer')[];
  /**
   * Optional link to the hashable staff identifier so users can be archived without losing staff id continuity.
   */
  staffRecord?: (string | null) | Staff;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: string;
  displayName: string;
  /**
   * Organisation-issued identifier — not an email.
   */
  staffId: string;
  staffIdHash?: string | null;
  /**
   * Drives who appears in validator, healthcheck, and crew-lead dropdowns.
   */
  capabilities?: ('validator' | 'assessor' | 'crewLead')[] | null;
  /**
   * Locks automatically on first on-chain reference. After that, the Staff ID can't change.
   */
  frozen?: boolean | null;
  /**
   * Optional — lets this person log in to the dashboard.
   */
  linkedUser?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: string | null;
  purpose?: ('area-metadata' | 'checkin' | 'report' | 'healthcheck' | 'misc') | null;
  /**
   * Content-addressed hash reproducing what the SDK would hash. Set lazily when the media is first referenced from an attestation.
   */
  storageHash?: string | null;
  /**
   * Flipped true once the file is IPFS-pinned.
   */
  pinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsor {
  id: string;
  displayName: string;
  kind: 'corporate' | 'municipal' | 'grant' | 'volunteer';
  canonicalKey?: {
    sponsorId?: string | null;
    contractNumber?: string | null;
    grantId?: string | null;
  };
  notes?: string | null;
  canonicalJson?: string | null;
  /**
   * Empty for volunteer sponsors.
   */
  commissionRefHash?: string | null;
  /**
   * Locks automatically on first use. After that, identification fields can't change.
   */
  frozen?: boolean | null;
  /**
   * Hide from dropdowns without deleting history.
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gardeners".
 */
export interface Gardener {
  id: string;
  displayName: string;
  email?: string | null;
  /**
   * Optional for now — required once gardeners self-attest from the mobile app.
   */
  wallet?: string | null;
  notes?: string | null;
  /**
   * Only active gardeners can be assigned to intervention crews.
   */
  status: 'onboarding' | 'active' | 'inactive';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas".
 */
export interface Area {
  id: string;
  name: string;
  /**
   * Internal identifier such as RM-PIGN-042.
   */
  areaId: string;
  municipality: string;
  areaType: '0' | '1' | '2' | '3' | '4';
  latitude: number;
  longitude: number;
  extendedMetadata?: {
    surfaceAreaSqm?: number | null;
    boundaryGeojson?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    coverPhoto?: (string | null) | Media;
    gallery?: (string | Media)[] | null;
  };
  /**
   * Empty when no extended details are set.
   */
  metadataHash?: string | null;
  /**
   * Populated on registration — inspect only.
   */
  attestation?: (string | null) | Attestation;
  lifecycleStatus: 'draft' | 'registering' | 'registered' | 'failed';
  activities?: {
    docs?: (string | Activity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attestations".
 */
export interface Attestation {
  id: string;
  uid: string;
  schemaName:
    | 'ScheduledIntervention'
    | 'AdminValidation'
    | 'PublishedIntervention'
    | 'AreaRegistration'
    | 'GardenerCheckin'
    | 'GardenerCheckout'
    | 'GardenerReport'
    | 'Healthcheck';
  signedAttestation:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timestampTxHash?: string | null;
  onchainTimestamp?: number | null;
  chainIdSnapshot?: number | null;
  attesterWallet?: string | null;
  status: 'committed' | 'failed';
  error?: string | null;
  relatedCollection?: string | null;
  relatedId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  type: 'checkin' | 'checkout' | 'report' | 'healthcheck';
  intervention?: (string | null) | Intervention;
  area?: (string | null) | Area;
  parentActivity?: (string | null) | Activity;
  gardener?: (string | null) | Gardener;
  claimedTimestamp: string;
  latitude?: number | null;
  longitude?: number | null;
  actualMinutes?: number | null;
  tasksCompleted?: string | null;
  taskCount?: number | null;
  notes?: string | null;
  healthScore?: number | null;
  assessor?: (string | null) | Staff;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metadataHash?: string | null;
  priorHealthcheck?: (string | null) | Attestation;
  photo?: (string | null) | Media;
  photoHash?: string | null;
  attestation?: (string | null) | Attestation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interventions".
 */
export interface Intervention {
  id: string;
  interventionId: string;
  area: string | Area;
  interventionType: '0' | '1' | '2' | '3' | '4' | '5';
  description: string;
  commissioning: {
    sponsor: string | Sponsor;
    commissionRefHashAtSchedule?: string | null;
  };
  crew?:
    | {
        gardener: string | Gardener;
        isCrewLead?: boolean | null;
        id?: string | null;
      }[]
    | null;
  crewSize?: number | null;
  scheduling?: {
    scheduledDate?: string | null;
    estimatedMinutes?: number | null;
    attestation?: (string | null) | Attestation;
  };
  validation?: {
    validator?: (string | null) | Staff;
    approved?: boolean | null;
    qualityScore?: number | null;
    feedback?: string | null;
    attestation?: (string | null) | Attestation;
  };
  /**
   * Populated when the intervention is revoked or fails mid-lifecycle.
   */
  revocation?: {
    reason?: string | null;
    revokedAt?: string | null;
    revokedScheduleUID?: string | null;
    failedFrom?: ('draft' | 'scheduled' | 'in_progress' | 'validated') | null;
  };
  lifecycleStatus: 'draft' | 'scheduled' | 'in_progress' | 'validated' | 'published' | 'revoked' | 'failed';
  publishAttestation?: (string | null) | Attestation;
  activities?: {
    docs?: (string | Activity)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidenceBundles".
 */
export interface EvidenceBundle {
  id: string;
  intervention: string | Intervention;
  /**
   * Captured at build time.
   */
  interventionIdSnapshot?: string | null;
  areaUIDSnapshot?: string | null;
  bundleVersion?: string | null;
  evidenceBundleHash?: string | null;
  offchainCount?: number | null;
  crewMembers?:
    | {
        gardener?: (string | null) | Gardener;
        attesterWallet?: string | null;
        checkin?: (string | null) | Activity;
        checkout?: (string | null) | Activity;
        report?: (string | null) | Activity;
        id?: string | null;
      }[]
    | null;
  scheduledRef?: string | null;
  validationRef?: (string | null) | Attestation;
  healthcheckActivity?: (string | null) | Activity;
  verification?: {
    valid?: boolean | null;
    attestationCount?: number | null;
    expectedCount?: number | null;
    temporalOrderValid?: boolean | null;
    timestampsVerified?: boolean | null;
    healthcheckOrderValid?: boolean | null;
    executionDateBracketed?: boolean | null;
    validationApproved?: boolean | null;
    lastVerifiedAt?: string | null;
    checksJson?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Publish is disabled until empty.
   */
  buildIssuesJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  lastError?: string | null;
  bundleJson?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  bundleState: 'draft' | 'built' | 'uploaded' | 'published' | 'verified' | 'failed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'registerArea'
          | 'scheduleIntervention'
          | 'commitActivityChain'
          | 'validateIntervention'
          | 'publishIntervention'
          | 'buildBundle'
          | 'verifyBundle';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'registerArea'
        | 'scheduleIntervention'
        | 'commitActivityChain'
        | 'validateIntervention'
        | 'publishIntervention'
        | 'buildBundle'
        | 'verifyBundle'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'sponsors';
        value: string | Sponsor;
      } | null)
    | ({
        relationTo: 'staff';
        value: string | Staff;
      } | null)
    | ({
        relationTo: 'gardeners';
        value: string | Gardener;
      } | null)
    | ({
        relationTo: 'areas';
        value: string | Area;
      } | null)
    | ({
        relationTo: 'interventions';
        value: string | Intervention;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'evidenceBundles';
        value: string | EvidenceBundle;
      } | null)
    | ({
        relationTo: 'attestations';
        value: string | Attestation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  roles?: T;
  staffRecord?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  purpose?: T;
  storageHash?: T;
  pinned?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors_select".
 */
export interface SponsorsSelect<T extends boolean = true> {
  displayName?: T;
  kind?: T;
  canonicalKey?:
    | T
    | {
        sponsorId?: T;
        contractNumber?: T;
        grantId?: T;
      };
  notes?: T;
  canonicalJson?: T;
  commissionRefHash?: T;
  frozen?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  displayName?: T;
  staffId?: T;
  staffIdHash?: T;
  capabilities?: T;
  frozen?: T;
  linkedUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gardeners_select".
 */
export interface GardenersSelect<T extends boolean = true> {
  displayName?: T;
  email?: T;
  wallet?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "areas_select".
 */
export interface AreasSelect<T extends boolean = true> {
  name?: T;
  areaId?: T;
  municipality?: T;
  areaType?: T;
  latitude?: T;
  longitude?: T;
  extendedMetadata?:
    | T
    | {
        surfaceAreaSqm?: T;
        boundaryGeojson?: T;
        coverPhoto?: T;
        gallery?: T;
      };
  metadataHash?: T;
  attestation?: T;
  lifecycleStatus?: T;
  activities?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interventions_select".
 */
export interface InterventionsSelect<T extends boolean = true> {
  interventionId?: T;
  area?: T;
  interventionType?: T;
  description?: T;
  commissioning?:
    | T
    | {
        sponsor?: T;
        commissionRefHashAtSchedule?: T;
      };
  crew?:
    | T
    | {
        gardener?: T;
        isCrewLead?: T;
        id?: T;
      };
  crewSize?: T;
  scheduling?:
    | T
    | {
        scheduledDate?: T;
        estimatedMinutes?: T;
        attestation?: T;
      };
  validation?:
    | T
    | {
        validator?: T;
        approved?: T;
        qualityScore?: T;
        feedback?: T;
        attestation?: T;
      };
  revocation?:
    | T
    | {
        reason?: T;
        revokedAt?: T;
        revokedScheduleUID?: T;
        failedFrom?: T;
      };
  lifecycleStatus?: T;
  publishAttestation?: T;
  activities?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  type?: T;
  intervention?: T;
  area?: T;
  parentActivity?: T;
  gardener?: T;
  claimedTimestamp?: T;
  latitude?: T;
  longitude?: T;
  actualMinutes?: T;
  tasksCompleted?: T;
  taskCount?: T;
  notes?: T;
  healthScore?: T;
  assessor?: T;
  metadata?: T;
  metadataHash?: T;
  priorHealthcheck?: T;
  photo?: T;
  photoHash?: T;
  attestation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "evidenceBundles_select".
 */
export interface EvidenceBundlesSelect<T extends boolean = true> {
  intervention?: T;
  interventionIdSnapshot?: T;
  areaUIDSnapshot?: T;
  bundleVersion?: T;
  evidenceBundleHash?: T;
  offchainCount?: T;
  crewMembers?:
    | T
    | {
        gardener?: T;
        attesterWallet?: T;
        checkin?: T;
        checkout?: T;
        report?: T;
        id?: T;
      };
  scheduledRef?: T;
  validationRef?: T;
  healthcheckActivity?: T;
  verification?:
    | T
    | {
        valid?: T;
        attestationCount?: T;
        expectedCount?: T;
        temporalOrderValid?: T;
        timestampsVerified?: T;
        healthcheckOrderValid?: T;
        executionDateBracketed?: T;
        validationApproved?: T;
        lastVerifiedAt?: T;
        checksJson?: T;
      };
  buildIssuesJson?: T;
  lastError?: T;
  bundleJson?: T;
  bundleState?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attestations_select".
 */
export interface AttestationsSelect<T extends boolean = true> {
  uid?: T;
  schemaName?: T;
  signedAttestation?: T;
  timestampTxHash?: T;
  onchainTimestamp?: T;
  chainIdSnapshot?: T;
  attesterWallet?: T;
  status?: T;
  error?: T;
  relatedCollection?: T;
  relatedId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizationProfile".
 */
export interface OrganizationProfile {
  id: string;
  name: string;
  legalEntity?: string | null;
  description?: string | null;
  website?: string | null;
  logo?: (string | null) | Media;
  attesterWalletPublic?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taskCatalog".
 */
export interface TaskCatalog {
  id: string;
  tasks?:
    | {
        code: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizationProfile_select".
 */
export interface OrganizationProfileSelect<T extends boolean = true> {
  name?: T;
  legalEntity?: T;
  description?: T;
  website?: T;
  logo?: T;
  attesterWalletPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taskCatalog_select".
 */
export interface TaskCatalogSelect<T extends boolean = true> {
  tasks?:
    | T
    | {
        code?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRegisterArea".
 */
export interface TaskRegisterArea {
  input: {
    areaId: string;
  };
  output: {
    chainUID: string;
    txHash: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskScheduleIntervention".
 */
export interface TaskScheduleIntervention {
  input: {
    interventionId: string;
  };
  output: {
    chainUID: string;
    timestampTxHash: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCommitActivityChain".
 */
export interface TaskCommitActivityChain {
  input: {
    activityId: string;
  };
  output: {
    chainUID: string;
    attestationId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskValidateIntervention".
 */
export interface TaskValidateIntervention {
  input: {
    interventionId: string;
  };
  output: {
    chainUID: string;
    timestampTxHash: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPublishIntervention".
 */
export interface TaskPublishIntervention {
  input: {
    interventionId: string;
  };
  output: {
    chainUID: string;
    txHash: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskBuildBundle".
 */
export interface TaskBuildBundle {
  input: {
    bundleId: string;
  };
  output: {
    evidenceBundleHash: string;
    attestationCount: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskVerifyBundle".
 */
export interface TaskVerifyBundle {
  input: {
    bundleId: string;
  };
  output: {
    valid: boolean;
    attestationCount: number;
    expectedCount: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}