import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  workspaces: {
    '.': {
      ignoreDependencies: ['@biomejs/biome', '@changesets/cli', 'knip', 'jscpd'],
    },
    'apps/webapp': {
      // knip auto-detects Next.js and Payload via plugins
      ignore: [
        'src/payload-types.ts', // auto-generated by `payload generate:types`
      ],
      ignoreDependencies: [
        'dotenv', // loaded via next.config / payload.config at runtime
      ],
    },
    'packages/sdk': {
      entry: ['src/index.ts', 'scripts/*.ts'],
      project: ['src/**/*.ts'],
    },
  },
};

export default config;
